default: styles/application.scss
contrast: styles/contrast.scss
mastodon-light: styles/mastodon-light.scss
sidem_altessimo: styles/sidem_altessimo.scss
sidem_beit: styles/sidem_beit.scss
sidem_cafeparade: styles/sidem_cafe_parade.scss
sidem_dramaticstars: styles/sidem_dramatic_stars.scss
sidem_flags: styles/sidem_f_lags.scss
sidem_frame: styles/sidem_frame.scss
sidem_highjoker: styles/sidem_high_joker.scss
sidem_jupiter: styles/sidem_jupiter.scss
sidem_legenders: styles/sidem_legenders.scss
sidem_mofumofuen: styles/sidem_mofumofuen.scss
sidem_sai: styles/sidem_sai.scss
sidem_sem: styles/sidem_sem.scss
sidem_shinsokuikkon: styles/sidem_shinsoku_ikkon.scss
sidem_kogado: styles/sidem_the_kogado.scss
sidem_w: styles/sidem_w.scss
